### ISSUE TITLE
Android APK manifest parse error

### ISSUE THREAD

**Issue by mkg20001** [Siderus/Orion#115]
**Describe the bug**
The AndroidManifest.xml fails to get parsed

**To Reproduce**
1. Go to the releases page
2. Download the v0.5.0 APK
3. Install the APK via ADB on LineageOS 15.1 (Android Oreo 8.1)

**Expected behavior**
The app gets installed as it is supposed to

**Screenshots**
![screenshot cli](https://user-images.githubusercontent.com/7735145/40351011-a721612e-5dab-11e8-931a-6bc985e9df84.png)

**Desktop (please complete the following information):**
 - OS: Android Oreo / LineageOS
 - Browser N/A
 - Version 8.1 / 15.1

**Additional context**
Exact error:
```
adb: failed to install APKs/Orion-0.5.0.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl83566788.tmp/base.apk: AndroidManifest.xml]
```

**Comment by koalalorenzo** [comment]
Sorry to inform you that the APK is not for mobile/Android, but it is for Alpine Linux. 

This application is designed (for now) only for Desktop (Windows, several GNU/Linux distributions and macOS). If you want to post it for Android, a PR is more than welcome :-)

**Comment by mkg20001** [comment]
So it looks like there is no android release (...yet ;) ), so I can close this now.

**Comment by koalalorenzo** [comment]
I am so sorry for the confusion

**Comment by mkg20001** [comment]
> I am so sorry for the confusion

Not your fault. But maybe add a note about that on the release page.
