### ISSUE TITLE
Send To/Share feature integration with OS

### ISSUE THREAD

**Issue by DonaldTsang** [Siderus/Orion#126]
- [x] "Send To" option similar to https://github.com/marcin212/ipfs-gui
- [x] Support for https://github.com/ipfs-shipyard/ipfs-companion

**Comment by koalalorenzo** [comment]
Hi! Thank you for this feature request.
It seems a little bit complicated than what I thought, but I think it can be achieved. If you want to contribute, feel free to drop more details and/or opening a new Pull Request! :)

The "Send To" is in the plan, not sure when, but it will be integrated not only with Windows Share options, but also with Mac services 👍

**Comment by DonaldTsang** [comment]
Don't forget Linux!  
Also, this link might have a few hints on teh whole IPFS+I2P/TOR situation https://ipfs.io/ipfs/QmYKQvBsbYrRhdaGvQXcEoSam7s5gKVYULfRgNPzN5JM8N/IPFS-via-OnionCat.html

**Comment by koalalorenzo** [comment]
Sorry, the "share" options with linux could be a little bit more difficult due to different IDE :( I will look in some more docs for gnome, but I think some help is needed for that integration :) 

Should we split this into multiple issues? One for the "share" feature, and keeping this one for the TOR network?

**Comment by DonaldTsang** [comment]
That would be good as well.

**Comment by koalalorenzo** [comment]
IPFS companion already works with it :) 
Let me rename this issue to support for Sharing feature (as this will not only cover Windows)

**Comment by koalalorenzo** [comment]
Fixed in #168 (It has to be enabled manually in the setting for now)
