### ISSUE TITLE
Hydrus IPFS support

### ISSUE THREAD

**Issue by DonaldTsang** [Siderus/Orion#128]
Try adding images to an IPFS folder using this image archiving client.  
https://github.com/hydrusnetwork/hydrus

**Comment by koalalorenzo** [comment]
Could you describe more the request here? this a feature request, right?
What are you expecting to have implemented? Plz Describe alternatives you've considered, as well as the solution you'd like to see!

**Comment by DonaldTsang** [comment]
Hydrus has in-built IPFS support, but it would be more convenient to show what IPFS folders has been pinned in Orion so that it can be easily viewed.

**Comment by koalalorenzo** [comment]
If Hydrus is using the `go-ipfs` api, you can just keep Orion running in the background while running Hydrus. Then you will find all your files pinned (as long as Hydrus is pinning them) in Orion! :)

let me know if this is helpful

**Comment by DonaldTsang** [comment]
That is exactly what I am talking about.

**Comment by koalalorenzo** [comment]
Perfect, I will close this then! It seems that we already support this (is part of our features) 

I will add a task in the backlog: add a better explanation to say that Siderus Orion works with all the other dapps, out of the box! :)
