### ISSUE TITLE
Interplanetary Wayback integration

### ISSUE THREAD

**Issue by DonaldTsang** [Siderus/Orion#131]
- [ ] Uses the library https://github.com/oduwsdl/ipwb to archive websites
- [ ] Has the ability to archive whole blogs when given a link

External reference: https://github.com/oduwsdl/ipwb/issues/388

**Comment by koalalorenzo** [comment]
Hi!
Thank you for reporting this: Have you tried it before? It is supposed to work as long as you keep Orion running in the tray icon / background. 

:) Closing this. Please update the format of your issues by answering the questions in the form! It will help us a lot!

**Comment by DonaldTsang** [comment]
@koalalorenzo I meant actually having an option to select a website WITHIN the dashboard, where it should reside under the "plus" button.
