### ISSUE TITLE
UI/UX: Row does not stay highlighted after being clicked

### ISSUE THREAD

**Issue by machawk1** [Siderus/Orion#134]
**Describe the bug**
Item list in main UI does not stay selected but is instead deselected onmouseup. Perhaps it is just the multi-column listbox used, but it is reminiscent of other familiar lists like Finder windows. This is immediately unfamiliar and confusing when the item will not stay "selected".

**To Reproduce**
1. Open the main UI.
2. Click on a list item, noting that it highlights so long as the mouse stay pressed.
3. Complete the click of the row, noting that the item's selection is tied to onmousedown instead of staying selected after the click has completed.

**Expected behavior**
When clicking a row, it remains selected after the onmouseup event.

**Screenshot**
![bug](https://user-images.githubusercontent.com/2514780/41176926-38b96a3c-6b30-11e8-8b28-a3307208d56b.gif)

**Desktop:**
macOS 10.13.5, Orion 0.6.0 from the .zip

**Comment by koalalorenzo** [comment]
Thx for reporting, it is very similar to one of the issues on #130 :)
We are working on it, probably in 2-3 weeks.

**Comment by koalalorenzo** [comment]
The current solution is to use the checkbox next to hash
