### ISSUE TITLE
UI: Various issues with the deletion dialog

### ISSUE THREAD

**Issue by machawk1** [Siderus/Orion#136]
**Describe the bug**
When deleting a file, a dialog appears to confirm the delete. This has multiple issues that would make it more intuitive and useful.

- [x] Ok-Cancel positioning (see [this post](https://www.factorio.com/blog/post/fff-246) on cross-platform considerations)
- [x] Snarky "Of course, Duh!" hurts usability.
- [x] An answer to "Are you sure?" should not be "Abort".
- [x] Listing the hashes to be deleted is far less useful than showing other information like the file sizes and/or names, which are available in the caller window.

**To Reproduce**
1. Select one or more items in the Orion UI.
2. Select the delete button.
3. Note the dropdown confirmation box.

**Expected behavior**
An intuitive, more clear interface. The options in this dialog may cause deletion of the user's data (by design), so clarity should be quite important.

**Screenshots**
![screen shot 2018-06-09 at 11 34 07 am](https://user-images.githubusercontent.com/2514780/41193408-31748a5a-6bd9-11e8-801b-76ab6b7a1b32.png)

**Desktop**
macOS 10.13.5, Orion 0.6.0

**Comment by koalalorenzo** [comment]
Working on pull request #139
Feedback/ideas are more than appreciated, @machawk1 ! :)

**Comment by koalalorenzo** [comment]
Changing to this: 
<img width="431" alt="screen shot 2018-06-18 at 18 27 42" src="https://user-images.githubusercontent.com/33528/41549202-5c19b99e-7325-11e8-8c2b-a852c972327e.png">

**Comment by machawk1** [comment]
@koalalorenzo This is quite a bit more descriptive of the files to be deleted -- a welcomed improvement.

![screen shot 2018-06-19 at 2 25 30 pm](https://user-images.githubusercontent.com/2514780/41616762-cb423b6e-73cc-11e8-9b8e-7c31e0a15559.png)


The Ok/Cancel positioning issue remains on macOS. For example, when emptying the Finder trash (the example I could most quickly recollect with this dialog pattern), the actionable/default is on the right.
<img width="532" alt="screen shot 2018-06-19 at 2 27 06 pm" src="https://user-images.githubusercontent.com/2514780/41616821-fa16efe8-73cc-11e8-8bfe-9d5c8703151d.png">

For multiple files (screenshot above), the information could use some alignment tweaks for aesthetics. Since it's tabular-esque, maybe align it in some way to replicate this effect. This improvement may be beyond the scope of this GitHub issue.

^ tested with Orion 1db7d7c4430cf42b0c90778520063cc32b03907d built from source (v. 0.6.0 current master branch).

**Comment by koalalorenzo** [comment]
I will keep the issue open, even if #139 has been merged... 
Probably we need to work a little bit more on that.

Thanks for helping!

**Comment by koalalorenzo** [comment]
First step has been released in 0.6.1
Next step:

- [ ] Use standardised position/order of buttons

**Comment by koalalorenzo** [comment]
0.7 was released. The issue about sorting the position of buttons has been added. 
Closing this! Let us know if you have more feedback @machawk1 :her

**Comment by machawk1** [comment]
@koalalorenzo Are there plans to resolve the positioning of the buttons per above. 

Orion v0.7:
<img width="837" alt="screen shot 2018-07-07 at 11 35 20 am" src="https://user-images.githubusercontent.com/2514780/42412409-e1d6659c-81d9-11e8-92a6-f24a5686d23f.png">
macOS Finder:
<img src="https://user-images.githubusercontent.com/2514780/41616821-fa16efe8-73cc-11e8-8bfe-9d5c8703151d.png">

**Comment by machawk1** [comment]
Also, related to this and perhaps a separate ticket, hitting Escape at this dialog does not close/cancel as is the usability convention.

**Comment by koalalorenzo** [comment]
I will open two new issues! We are tracking the issues anyway on GitLab, as many of them are including multiple stories/requests to work on! :-) 

Thank you so much, btw! It is a huge help your feedback for us!
