### ISSUE TITLE
Bad link to issue board in README

### ISSUE THREAD

**Issue by machawk1** [Siderus/Orion#149]
**Describe the bug**
In the README under the "How to Help" section there is a link to the "Issue Board" that points to https://dev.siderus.io/projects/Orion/agile/board. This link either appears to be down (as of July 7, 2018 11:45 EST) or incorrect, as the URI does not resolve.

**To Reproduce**
Click/curl the link in the README. Using the latter method returns:
```sh
$ curl https://dev.siderus.io/projects/Orion/agile/board
curl: (6) Could not resolve host: dev.siderus.io
```

**Expected behavior**
Some Web page/interface is shown.

**Screenshots**
<img width="508" alt="screen shot 2018-07-07 at 11 47 35 am" src="https://user-images.githubusercontent.com/2514780/42412499-94396242-81db-11e8-8642-1ac6dd1b73fb.png">

**Desktop (please complete the following information):**
macOS 10.13.5, Google Chrome 67.0.3396.99

**Comment by koalalorenzo** [comment]
We are currently moving from Github + Private Redmine to GitLab. We will update the links. We would like to not confuse users (GitHub vs GitLab) so we have to decide what/where to publish commits, issues. At the moment the board is private together with other services we are developing.

We will remove the link and then close this issue! Thanks for reporting! 👍

**Comment by koalalorenzo** [comment]
Forgot to say: If you want to help, we still push our code on GitHub, so we are happy to receive PR on open Issues that are not marked as "in progress"! I will make sure to write that in the readme file 😄
