### ISSUE TITLE
Option for an analytics-free version of the Orion build

### ISSUE THREAD

**Issue by DonaldTsang** [Siderus/Orion#152]
Problem: Orion allows people to choose whether to opt-in to data analytics in Orion, but for the security-minded they would want it gone from their computer on the get-go  
Solution: Provide a build variable that allows the complete removal of data analytics from the binary (excluding notification regarding updates)

**Comment by koalalorenzo** [comment]
We are already providing this option as an OptIn, so you can just disable the feature! We do respect privacy. We need to know what we should focus more and do some testing, that is why we have it as an opt-in: if you want to help us that is the best way! 

At the same time it is not possible to have a get-go as the wizard is designed to explain basic concepts and ease the users into the process of set up.

Read more on our goal here: https://blog.siderus.io/siderus-orion-ipfs-is-for-everybody-d2fff304c992?source=github

**Comment by DonaldTsang** [comment]
@koalalorenzo I was describing those who are "tinfoil-proofing" their computer (Similar to https://prism-break.org/en/) (excuse my language)

**Comment by koalalorenzo** [comment]
I am thinking more about the users that this app is designed for. I found this a nice idea, but I am not sure we want to spend some time to do that, while the user can already decide to opt-in at the beginning. I am not sure I see this as a requirement, that is all!
