### ISSUE TITLE
Add a PPA/repo for ubuntu

### ISSUE THREAD

**Issue by mkg20001** [Siderus/Orion#153]
This would allow auto-updates of the debian package.
I've create a simple repo @ https://deb.mkg20001.io/orion with https://github.com/mkg20001/ppa-script ([config used](https://ipfs.io/ipns/deb.mkg20001.io/config.orion.sh))
_(This could - and should - be moved to the Siderus infrastructure)_

Installing the PPA:
```sh
curl -s https://deb.mkg20001.io/key.asc | sudo apt-key add -
echo "deb https://deb.mkg20001.io/orion $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/orion.list
```

**Comment by koalalorenzo** [comment]
I think we can automate this with GitLab pipeline, so you don't have to update this manually...
I will add a task for this 👍 

Thx!

**Comment by mkg20001** [comment]
> I think we can automate this with GitLab pipeline, so you don't have to update this manually...

Currently it's not manual either, it just uses a cronjob. Although using a GitLab pipeline to generate the repo on every release is definitively a better idea.
(Just some more suggestions: The key for signing the repo might be added to the job as secret env variable so no manual work is needed and the repo could be published over IPFS, too)

**Comment by koalalorenzo** [comment]
that is an awesome idea!

If you want you can add a new target in the makefile and send a PR :) Do you have time for it?

I will take care of setting up the pipeline on GitLab and publish on IPFS! \o/

**Comment by mkg20001** [comment]
> If you want you can add a new target in the makefile and send a PR :) Do you have time for it?

Yes!

> I will take care of setting up the pipeline on GitLab and publish on IPFS! \o/

re: publish to IPFS https://github.com/mkg20001/ipfs-dnslink-update "automate all the things!"

**Comment by mkg20001** [comment]
:tada: https://github.com/Siderus/Orion/pull/154

**Comment by koalalorenzo** [comment]
Worth checking: https://github.com/Siderus/Orion/pull/166 :D
