### ISSUE TITLE
TOR with Orion

### ISSUE THREAD

**Issue by DonaldTsang** [Siderus/Orion#188]
**Is your feature request related to a problem? Please describe.**

Default GUI option to allow TOR to be used with Orion.
Orion will be automatically packaged with this feature either through the installation process, or through "customized versions" on the website

https://github.com/OpenBazaar/go-onion-transport is a Go library made to be used with Go-IPFS

**Describe the solution you'd like**

**Describe alternatives you've considered**

I2P+IPFS has yet been created by other IPFS projects

**Additional context**

**Comment by DonaldTsang** [comment]
Sorry for duplicates, I will add the info to the other suggestion

**Comment by koalalorenzo** [comment]
Duplicate with 
https://github.com/Siderus/Orion/issues/127
