### ISSUE TITLE
Conflicting distribution warning from APT

### ISSUE THREAD

**Issue by NatoBoram** [Siderus/Orion#190]
**Describe the bug**

`W: Conflicting distribution: https://get.siderus.io apt/ Release (expected apt/ but got debian)`

**To Reproduce**
1. Follow instructions [here](https://github.com/Siderus/Orion#ubuntu--debian-repository)

**Expected behavior**

`All packages are up to date.`

**Screenshots**

![image](https://user-images.githubusercontent.com/10495562/45071104-af7a0480-b0a2-11e8-9811-34a665437ab1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS x86_64

**Comment by koalalorenzo** [comment]
Yes, there is a conflicting distribution warning, but you are still able to install the package.

We will fix that when we will have more time. Now we are in the process of restructuring and redesign the app for better performances.

**Comment by koalalorenzo** [comment]
@NatoBoram Now that we have released `ipfs` for `armhf` (ex: RaspberryPi) we should have fixed this issue. I have tested it, but can you confirm? I will close this issue only if you confirm in few days 👍

**Comment by koalalorenzo** [comment]
Closes, in case it appears you might need to remove the repository from the source list, then update and then re add it.
