### ISSUE TITLE
IPNS Key Generator

### ISSUE THREAD

**Issue by TheChiefMeat** [Siderus/Orion#193]
Currently the only thing keeping me from switching over from go-ipfs to the Orion client is the lack of individual key generation so I can publish to seperate IPNS addresses. Are there any plans for such a feature to be added? If not, please consider this to be a request :)

**Comment by koalalorenzo** [comment]
Yes, We have plans for this features for the version `1.0` coming soon 👍 

The min ETA could be 1-2 months, but for sure before the end of the year. The main reason is that we are packing it with a redesign as well a deep restructure of the code (by using also new tools to improve drastically the user experience 😉 ).

If you are interested and you want to know more you can subscribe to [Siderus Newsletter](
http://eepurl.com/dfB6q5). We will lunch a survey in few weeks to collect even more feedback and make the app better.

**Comment by TheChiefMeat** [comment]
Thanks for the reply :)

**Comment by koalalorenzo** [comment]
Closing as this feature has been implemented in the beta :)
