### ISSUE TITLE
Writable Gateway Toggle Switch

### ISSUE THREAD

**Issue by TheChiefMeat** [Siderus/Orion#194]
Would like to see a toggle switch to make the gateway writeable, should be easy to implement; the config file simply needs the "Writable": false flag changed on toggle, and then close the ipfs daemon and restart orion.

Edit: Would also be a good idea to have just below that an option to set the amount of space allocated to the writeable gateway (how much one can write to the gateway), currently set with the "StorageMax": "10GB" flag

**Comment by koalalorenzo** [comment]
You can modify the configuration of the daemon by opening the `config` file in the repo path.

From the settings you can open the directory:
<img width="837" alt="screen shot 2018-09-14 at 09 07 29" src="https://user-images.githubusercontent.com/33528/45535155-d1d7f480-b7fd-11e8-8a16-1c3e696259b9.png">

And then you can edit the `config` file where you can enable the features you want:
<img width="804" alt="screen shot 2018-09-14 at 09 09 16" src="https://user-images.githubusercontent.com/33528/45535172-e0bea700-b7fd-11e8-9be8-5f39ac38267b.png">

After that it should be ok to just restart the app.

We don't have these features yet, I will mark this as a task and I will not close until we have it ready, but as we have already a "quick fix" it might be lower in priority (that said, we will work on it, don't worry!). Probably version for v1.0 (currently working on from GitLab).

Is that helping? Would you like to see more?

**Comment by TheChiefMeat** [comment]
No that's about it. I already knew how to set it in the config file, can't wait to see it in the client :)

**Comment by Noc2** [comment]
I just want to say this tool is really nice and would love to see this feature integrated. Could writable not even be the default option?  I’m currently developing and IPFS page (https://github.com/PACTCare/Dweb.page) myself and refused to integrate js ipfs for obvious reasons. With this simply installer people could use and develop a lot of awesome ipfs pages without all the command line stuff! Therefore it would be nice if it would be writable out of the box without changing any settings.

**Comment by koalalorenzo** [comment]
@Noc2 It is coming. The only thing we don't want to do is to change too much the default configuration but this might change in the future.

It would be nice if we could have the encryption system used as a library so we can implement it in the same way, and have a more "standard" way to share secret files! 👍

**Comment by Noc2** [comment]
For the encryption I simply use the Web Crypto API (AES256-GCM). It's relatively easy to use, see https://github.com/PACTCare/Dweb.page/blob/master/src/js/services/Encryption.js or https://github.com/diafygi/webcrypto-examples

**Comment by koalalorenzo** [comment]
Closing it as the beta release has implemented this feature.
It requires to restart the app/daemon but it works.

If you want to test the beta: https://orion.siderus.io/#/beta
