### ISSUE TITLE
File/Folder Nicknames

### ISSUE THREAD

**Issue by TheChiefMeat** [Siderus/Orion#196]
I just realised that if we're to make IPFS/IPNS easier to use, clients need an easier way of identifying content they are pinning at a glance. 

I'd like to request the ability to give the items you are pinning "nicknames", so that when you open the client, you can very easily see what you have pinned, instead of just seeing the hash (of course by default the hash would be there, but perhap a right-click option "Add nickname" would work).

**Comment by koalalorenzo** [comment]
We are solving this by providing at the moment also the file names, but that is not necessarily useful.

What about "tagging" features, like macOS does for organising/identifying content?

**Comment by TheChiefMeat** [comment]
As long as you can tell what the file/folder is at a glance, and solution can work. At the moment I can't tell with individual files because all I see is the hash and no file name.

![hashes](https://user-images.githubusercontent.com/17432768/45594602-a1c35980-b995-11e8-8829-3c7dacfe1799.png)

**Comment by koalalorenzo** [comment]
Weird, this is what Siderus Orion shows:

![screen shot 2018-09-16 at 10 52 13](https://user-images.githubusercontent.com/33528/45594661-b5bf8900-b99e-11e8-8444-6c33a71df146.png)

**Comment by TheChiefMeat** [comment]
I don't see that at all on the Windows client. Folders that have files in them have names, but single pinned files have nothing next to them

![filesnononno](https://user-images.githubusercontent.com/17432768/45594674-8b69cd80-b996-11e8-8840-7790622be11e.png)

**Comment by koalalorenzo** [comment]
Yes, this is due to the fact that those files were added without wrapping. Sadly this is an IPFS problem, and the only way to prevent this ATM is to wrap them. Have you added those files using Siderus Orion?

**Comment by TheChiefMeat** [comment]
I did but I don't think they were wrapped, I can try that too.

**Comment by TheChiefMeat** [comment]
Yeah, when I wrap them the file name shows, but unwrapped files don't have a file name.

**Comment by TheChiefMeat** [comment]
Something like this would be nice, just so we can easily reference names:

![2018-09-16_11-11-37](https://user-images.githubusercontent.com/17432768/45595304-60d14200-b9a1-11e8-9308-30e219676cef.gif)

**Comment by koalalorenzo** [comment]
👍 we will probably add this in the future versions after release of v1 👍 

I have added this thx!

**Comment by roscoevanderboom** [comment]
Here is an update! 

In 1.0 there is file description feature. Awesome! 

The "add Description" feature is great! Thanks a lot. As an enhancement, add tags (categories). This could help to filter content later. Is it possible to create something like this?

`var myHash = {
	some_name:{
	hash: "Q12e1wesd....",
	tags:["pics","family","holiday"]},
}`

i'm still learning JS :) please mind the simplicity

The "add Description" feature is a core aspect of keeping things organized. When adding, there could be a box with regularly used tags (ie. pics, docs, websiteResources) to help with adding quick, user-defined descriptions.

**Comment by koalalorenzo** [comment]
Yes, for now we are giving higher freedom to the user to select and write what they want in the description and then use full-text search to find what they need.

Tags might come later as those might be more limiting than a full text description. Having both might confuse the users. 

Anyway, I added this as a task :) Adding tags can help for sure, but it will be lower priority than a full-text search

**Comment by roscoevanderboom** [comment]
The full description is awesome!! I really like that it's not just a 1 word tag. The idea of tagging would be to assign multiple hashes to the same tag and also multiple tags to the same hash. 

This way I could manage project resources with Orion. Tag = MyBlog. Containing the hashes for the html, css, js and any other resources ( pictures, audio, icons ). The tag becomes like a folder and hashes could be sorted by date added. Now I have version control and it's easy to view only the content that relates to the project.

The same css files could also be tagged with another project name like Portfolio or Company. 
Now I can view and use the same file in multiple projects which removes a lot of duplication. 
Next, I update a file that might be relevant to multiple projects. The new hash is tagged, making it appear in any project that it was tagged to.  

I realize the goal behind IPFS is to improve the internet, but I think it's primary use can start in the file systems on our devices. Just about anything can be viewed through a web browser now or applications that use web technologies ( like Electron ). Combined with an ipfs datastore, which references data by content and not by address, it improves the way we interact with our data a lot! If multiple programs use the same hash and one program changes the content, it won't break the other programs, as the original hash is still there and referenced by other programs. 

The only thing missing is encryption!! But that is another topic....and I feel like this is becoming a blog post.....

**Comment by koalalorenzo** [comment]
Closing this as the beta release has this feature.
If you want to try it out here is the download link: https://orion.siderus.io/#/beta
