### ISSUE TITLE
Put a link to "What the hell is IPFS?" on your home page

### ISSUE THREAD

**Issue by DerKarlos** [Siderus/Orion#204]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by koalalorenzo** [comment]
Hello @DerKarlos could you explain a little bit more about what are you expecting exactly? Which homepage are you referring to? https://orion.siderus.io ?

**Comment by DerKarlos** [comment]
You should consider, one may come tho your homepage, NOT knowing about IPFS

Until today I did not know about IPFS or its clients.
On some ways I got to your https://orion.siderus.io
and found a list of features of the client and the text abowe says,
it is a client for IGFS.
Now I was courious and wanted to know, what the hell is IGFS
but I did not see a single hint or link to find out.

The "IPFS" in the top text could be a link to its homepage or Wikipedia.

**Comment by koalalorenzo** [comment]
I will keep this task as part of a bigger planned task for adding more content into our landin pages. 👍 

Thanks for the feedback!

**Comment by koalalorenzo** [comment]
I guess we should add it in the app as well

**Comment by koalalorenzo** [comment]
We have updated the new app (v1.0) with a "What is IPFS" with links to a video and the IPFS website.
This will appear when the users opens the app for the first time.

The v1.0 is in beta release at the moment. You can download it here: https://orion.siderus.io/#/beta
We will add a What is IPFS soon on the website

**Comment by roscoevanderboom** [comment]
The problem with some of the current documentation is that it is sometimes misleading or not impressive ( this is what my father said after watching Juan Bennet's talk ). 

One of the first points is that it is not a permanent web, as is claimed in many places.  You have to pin an item in your repo to keep it there. Thankfully, Orion combines the IPFS add and IPFS pin actions into 1 easy to manage action. 

Second, is the inability to manage dynamic content.  IPNS is an attempt....but compared to the live reloading of the DAT protocol, IPNS is a caveman. 

Most non-developers that I introduce IPFS to generally reply with...."Why the hell do I need this if I have dropbox?" or "The internet is fine, why try and re-invent the wheel?" Explaining content addressing kinda of gets them to understand why it's important to develop IPFS. 

Other developers are happy with the tools they currently use like Git, so they don't see the need.

**Comment by roscoevanderboom** [comment]
I stopped making tutorial videos because no one cared :(

**Comment by koalalorenzo** [comment]
ToDo:

- [X] Add video link in the App
- [ ] Add video link in the homepage
- [ ] Add short description in the homepage

**Comment by koalalorenzo** [comment]
The new website now includes a short description: http://orion.siderus.io/#/
I am closing this. In case, please feel free to comment or/and reopen!
