### ISSUE TITLE
Upload a shortcut folder

### ISSUE THREAD

**Issue by praviin02** [Siderus/Orion#205]
**Describe the bug**

Issue when uploading a shortcut folder or file

**To Reproduce**
1. Go to  upload
2. Click on add directory 
Add a "Short cut folder
 The app do not respond.

**Expected behavior**
The app should promt an error or something stating we cannot upload shortcut file or folder

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version : 0.9.1

**Additional context**

This issue can be low!!
But the app crashes which makes this high

**Comment by koalalorenzo** [comment]
I guess this is due to Windows handling the links/shortcuts in a different way. We will investigate into this. Thanks for reporting!
