### ISSUE TITLE
Unable to delete a folder after downloading

### ISSUE THREAD

**Issue by praviin02** [Siderus/Orion#206]
Unable to delete a folder after downloading

Download a folder from app.
keep the app open
try to delete the folder with hash.

until we close the app.
the folder do not delete.

We can delete the file inside the folder and then delete the file

**Comment by koalalorenzo** [comment]
Can you tell me more information about your OS? Do you have any logs or any more information?

Usually this due to the OS and the App (IPFS in this case). If you give use more info we can explore more into the issue

**Comment by praviin02** [comment]
Hi
I am using Windows 10.

Steps to replicate.
1.Upload a file
2.Download the file to desktop.
3.The file with folder downloads fine.
4.Now delete the downloaded folder.

We are unable to delete until we close the Orion app.

**Comment by koalalorenzo** [comment]
Thx, we will investigate this to be sure that this error will not appear in the new version of the app

**Comment by praviin02** [comment]
Thank you!

**Comment by koalalorenzo** [comment]
@praviin02 Have you tried the latest beta? Does this bug persist with that version?
You can download it from here https://orion.siderus.io/#/beta

**Comment by koalalorenzo** [comment]
@praviin02 please check it with the latest beta (v1.1)
You can download it from here https://orion.siderus.io/#/beta

In case I don't get any answer, in few days I will cloes this issue as I am not able to replicate the bug anymore!
