### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#209]
OS: Linux
Orion: 1.0
There are some responsiveness issues for smaller screens. 
In "Storage" section, hashes push the "actions" button out of view. 
In "Settings-Connectivity" section, the icons move over the ip4 addresses.

**Comment by koalalorenzo** [comment]
For now I might suggest to use the app as fullscreen, but we will work on it as we are planning to support also mobile.

Do you know the size of the screen you are using?
Is the problem happing only when you have the window resized? 

Btw, Thx for helping with the tests! ❤️

**Comment by roscoevanderboom** [comment]
I was just resizing the browser window. When going to tablet and mobile, the hashes will be too long to show. On those devices, icons with labels (tags....I'll open another on this ) are gonna work better.

**Comment by koalalorenzo** [comment]
Hello!
We are about to release a new version that fixes these issues :D (v1.0.2-beta) 
please download and install it. Let us know if the issues have been fixed! 

Please test it

**Comment by roscoevanderboom** [comment]
Got it. Display works perfectly now!
