### ISSUE TITLE
Electron Browser window

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#210]
Orion is an Electron app, right?
Is it possible for Orion to spawn its own browser windows to view links/content?

**Comment by koalalorenzo** [comment]
Yes, we prefer to not manage these things as a user might want to use the default browser of the OS (Ex: firefox, safari, chrome or anything he used in the settings). 

This is to ensure privacy and security, as if we use Orion itself as a browser we might get some security/privacy issues. 

What is the use case you are thinking about? What do you need a in-app browser for?

**Comment by roscoevanderboom** [comment]
I don't always want the default browser behavior for viewing some local files. Electron windows can be customized with menus and context menus. Or preview content windows.

I realize being a browser is not the main focus of Orion so this is not an important issue at all. Maybe in version, windows with custom behavior can be introduced.

**Comment by koalalorenzo** [comment]
Closing for now! Thank you!
