### ISSUE TITLE
hash is wrong when add directories with beta version 

### ISSUE THREAD

**Issue by royforu** [Siderus/Orion#211]
hi, 
when I use beta version to add directories, it shows wrong hash value on the screen.
Can someone replicate this behavior?
Thank you.

**Comment by koalalorenzo** [comment]
Can you make an example of wrong hash?

Maybe you want to disable wrapping in the settings.

**Comment by koalalorenzo** [comment]
By default when you are adding a new file/directory in Orion, it gets wrapped in a new directory, as if you were running:

```
ipfs add -r -w ./directory
```

This will create a new CID/Hash that points to a new directory which includes the original directory (which hash is correct). To see your hash directory you should be able to check the properties, and inside you will find your directory.

If you want to change this behaviour, you can check the settings. There should be an option (in both v0.9.1 and v1.0-beta) to disable wrapping files.

**Comment by royforu** [comment]
Sorry. I don't know add function is wrapped in a directory by default. 
Yes, it shows the correct hash value with wrap flag. 
Thanks for your kind reply. ^ ^

**Comment by koalalorenzo** [comment]
No problem! Let us know if you need any help! :-)
