### ISSUE TITLE
Spelling Mistake When Removing IPNS Key

### ISSUE THREAD

**Issue by TheChiefMeat** [Siderus/Orion#212]
Issue is title: Spelling Mistake When Removing IPNS Key

**Comment by koalalorenzo** [comment]
Where is it? In the button? Loading bars? Notifications? 😅 
Sorry and thank you for reporting 😛

**Comment by TheChiefMeat** [comment]
It's in the notification that appears when you remove it, at the bottom of the application, I just barely saw it as it popped up.

**Comment by TheChiefMeat** [comment]
![siderus orion_2018-12-09_20-43-27](https://user-images.githubusercontent.com/17432768/49702702-1b648f80-fbf3-11e8-8853-14a8717da128.png)

**Comment by koalalorenzo** [comment]
Fixed :D
