### ISSUE TITLE
windows integration - Orion window close

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#213]
Win10

Orion 1.0.4

Thx for adding windows integration again. 

The situation:

Orion running in background.
Add files/folders from windows explorer.
Open Orion to check files/folder.

Bug:

Orion browser window opens but closes immediately. The app is still running and when I open it again it is fine. Just the first time after adding a file, the window will close.

**Comment by koalalorenzo** [comment]
This bug will be fixed in next release planned for tomorrow: `v1.0.5-beta`

**Comment by roscoevanderboom** [comment]
fix confirmed
