### ISSUE TITLE
windows firewall prompt

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#214]
Every time I open Orion, Windows prompts me to allow connection through firewall. This was not the case with earlier versions of the beta. 

You mentioned it's an Asar packaging issue. Just thought I'd leave it here in case others encounter the same issue.

**Comment by koalalorenzo** [comment]
GitLab merge request: https://gitlab.com/siderus/orion/shell/merge_requests/53

**Comment by koalalorenzo** [comment]
@roscoevanderboom the latest beta version should have fixed this.
Download link: https://orion.siderus.io/#/beta

Could you check?

**Comment by roscoevanderboom** [comment]
No more problems here
