### ISSUE TITLE
Convert "Actions" menu context menu

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#215]
Currently Orion doesn't use any context menus. I suggest using the "Actions" menu. This will free up space in the UI and give users a more Native OS feel when interacting with files.  

Could "Open in Browser" be assigned to a double-click event? This will also make it feel like Native OS file explorers.

**Comment by koalalorenzo** [comment]
We can look into that.
I will plan for `v1.1` the inclusion of right-click actions 

Thank you for your feedback :)

**Comment by koalalorenzo** [comment]
We changed the behaviour of double click in `v1.1.1-beta` and added "Copy public URL". 
I am not sure, but I guess we can close this ticket. I will do so in few days if I don't get any answer back
