### ISSUE TITLE
storage list doesn't update

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#217]
win10

Orion 1.0.5

After removing a file/folder, notification is sent that action is complete. But filename is still in storage list. Only after reload or closing window and reopen is the change reflected.  So the file is being removed from repo but not from browser view.

Edit: It seems to be a general refresh issue. Also no change after "add file" or "change description". Only after reload

**Comment by koalalorenzo** [comment]
We have pushed a new version of the interface. No download/update required (the interface update is automatic) but in it still shows `v1.0.3-beta` in the About (under Settings) restart the app to clean automatically the cache.

Please let me us know if the error persists.
