### ISSUE TITLE
clean uninstall

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#222]
Orion installs files in many locations. Program Files\Siderus, AppData\Roaming\Siderus and AppData\Local. Is it necessary for the files to so spread out? Could the whole app not be contained in one folder? ie, Program Files\Siderus

Currently uninstalling Orion leaves many files on host system. It is good to keep repo for future installs but bad if user wants to remove repo or create fresh install. 

Could you add the option to remove all files? This will be helpful to people not so familiar with their OS and file system to remove unwanted files. I can find and remove all files manually but many people would not be able to do it.

**Comment by koalalorenzo** [comment]
It looks like something that we have to manually do (from the app). (Check: https://github.com/electron/windows-installer/issues/113 and maybe https://github.com/electron-userland/electron-builder/issues/1052 ). The "contained" vs "Spreadout" depends on Electron sadly.

To prevent data loss I would probably prefer to keep the data directory for now. Closing for now, hopefully Electron will have a better way to manage this.
