### ISSUE TITLE
"make run" fails without jq installed

### ISSUE THREAD

**Issue by useaquestion** [Siderus/Orion#223]
Just a note for documentation, "make run" will fail if you don't have the jq package installed. Installing it from the Ubuntu repos (I'm running 18.04) makes it work perfectly. 

It's also probably worth noting in documentation not to install node from repos, because this relies on v>=10

**Comment by koalalorenzo** [comment]
Yes, I will make sure to have it defined in a readme file.

**Comment by koalalorenzo** [comment]
I have updated the docs, closing this :) 

https://gitlab.com/siderus/orion/ui/blob/master/docs/RUN.md
https://gitlab.com/siderus/orion/shell/blob/master/docs/RUN.md
