### ISSUE TITLE
No icon fpr Manjaro Linux (Gnome)

### ISSUE THREAD

**Issue by tiotrom** [Siderus/Orion#224]
I am using the appimage on Manjaro and the appimagelauncher - I click the usual "run and integrate" but that does not create a .desktop file in .local/share/applications. Is there any way to fix this? Thank you very much for your work!

**Comment by koalalorenzo** [comment]
I am not sure, sometimes the Appimage launcher needs some extra dependencies installed in order to create and show the `.desktop` files.

This is a little outside my knowledge but probably this is more related to the distro and Electron. I am sorry.

If you find a solution, please let us know!

**Comment by tiotrom** [comment]
The thing is that it works with any other appimage, except Orion.

**Comment by koalalorenzo** [comment]
I am so sorry. Do you have any log? Can you give more information/screenshots so that I can try to replicate it in a vm? 

Thanks for helping :)

**Comment by tiotrom** [comment]
@koalalorenzo I think the best way to replicate in a VM is with a Linux distro + appimagelauncher package installed - https://github.com/TheAssassin/AppImageLauncher - Interestingly I tested the https://github.com/ipfs-shipyard/ipfs-desktop and it suffers from the same error. Maybe that's connected. I do not know what logs to send you to be honest....if I knew I would :D - but I am here if you want me to test anything,

**Comment by koalalorenzo** [comment]
I think it might be some missing dependencies, I remember having this issue with Ubuntu as well. 
I will close this issue for now, but I took note that if we stumble on it again I will write down on gitlab in the documentation how to solve the issue.

Thank you for helping reporting it!
